#version
apiVersion: v1
#set resource type as service
kind: Service
#add metadata
metadata:
  #set service name
  name: shipping-service
  #(optional) if using the namespace
  namespace: ecommerce-app 
  #labeling
  labels:
    app: shipping
spec:
  selector:
    #select pod by app
    app: shipping
  ports:
    #use TCP
    - protocol: TCP
    #listening to port
      port: 3001
  #set type to NodePort
  type: NodePort