#version
apiVersion: apps/v1
#set resource type as service
kind: Deployment
#add metadata
metadata:
  #set deployment name
  name: shipping-deployment
  #(optional) if using the namespace
  namespace: ecommerce-app 
  #labeling
  labels:
    app: shipping
spec:
  #set deployment replica
  replicas: 1
  selector:
    #select label that match
    matchLabels:
      app: shipping
  template:
    metadata:
      #labeling deployment
      labels:
        app: shipping
    spec:
      containers:
          #name the container
        - name: shipping-service
          #pull the image from github package
          image: ghcr.io/mueiya/dicoding-shipping-service:latest
          ports:
              #exposed port for container
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: AMQP_URL
              #set as amqp://<username>:<password>@rabbitmq:5672, 
              value: "amqp://mueiya:secretpassword@my-rabbitmq.default.svc.cluster.local:5672"
